baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Golang Tutorial'
theme = "hugo-theme-learn"
author = "Mo Really"


[params]
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30

